package cz.cvut.fel.omo.smarthome.enums;

public enum DeviceType {
    ENUM_AIR_CONDITIONER,
    ENUM_CD_PLAYER,
    ENUM_FRIDGE,
    ENUM_MICROWAVE,
    ENUM_TELEVISION,
    ENUM_WASHING_MACHINE,
    ENUM_AIR_CONDITIONING_SENSOR,
    ENUM_FRIDGE_SENSOR,
    ENUM_LIGHT_SENSOR,
    ENUM_OVEN_SENSOR,
    ENUM_TELEVISION_SENSOR,
    ENUM_THERMOMETER,
    ENUM_WASHING_MACHINE_SENSOR,
    ENUM_OVEN,
    ENUM_LIGHT
}
