package cz.cvut.fel.omo.smarthome.enums;

public enum EventType {
    ENUM_DIY_REPAIR_EVENT,
    ENUM_PERSON_MOVE_EVENT,
    ENUM_PET_MOVE_EVENT,
    ENUM_PET_SLEEP_EVENT,
    ENUM_WASHING_MACHINE_EVENT,
    ENUM_FRIDGE_EVENT,
    ENUM_HOUSE_BOOM_EVENT,
    ENUM_BUY_EVENT,
    ENUM_SERVICE_REPAIR,
    ENUM_AC_EVENT,
    ENUM_WATCH_TV,
    ENUM_LISTEN_TO_MUSIC,
    ENUM_LIGHT_TURN_ON,
    ENUM_LIGHT_TURN_OFF,
    ENUM_GO_SKIING_EVENT,
    ENUM_GO_BIKING_EVENT,
    ENUM_GO_RUNNING_EVENT,
    ENUM_OVEN_EVENT,
    ENUM_MICROWAVE_EVENT,
    ENUM_CLOSE_BLINDS_EVENT,
    ENUM_SLEEP_EVENT,
    ENUM_WORK_EVENT,
    ENUM_OPEN_BLINDS_EVENT
}

